vich_uploader:
    db_driver: orm
    mappings:
        edition_images:
            uri_prefix: /images/editions
            upload_destination: '%kernel.project_dir%/public/images/editions'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer